# Node.js
pool:
  name: local
  demands:
  - npm
  - Agent.Version -gtVersion 2.163.1

jobs:
- job: Build
  steps:
  - script: npm install
    displayName: 'Install Node.js dependencies'
  - script: npm run build
    displayName: 'Build Node.js project'
       npm test
   displayName: 'npm install, build, and test'

# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

